import { Injectable, OnModuleDestroy } from '@nestjs/common';
import { db } from './prisma/db.js'; // Generated by Prisma 8

@Injectable()
export class AppService implements OnModuleDestroy {
  async getHello() {
    // 1. Create a test user in PostgreSQL
    const newUser = await db.orm.public.User.create({
      email: `test_${Date.now()}@example.com`,
      name: 'Prisma 8 Test User',
    });

    // 2. Fetch all users currently in the database
    const allUsers = await db.orm.public.User.select(
      'id',
      'email',
      'name',
    ).all();

    return {
      message: 'Success! The Database is connected!',
      newlyCreated: newUser,
      totalUsersCount: allUsers.length,
      allUsers: allUsers,
    };
  }

  // 3. Clean up the database connection pool on server shutdown
  async onModuleDestroy() {
    await db.runtime().close();
  }
}
